name: forests-offsets-fire
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - aiohttp
  - awscli
  - beautifulsoup4
  - click
  - dask
  - fiona
  - fsspec
  - geopandas
  - git
  - mbutil
  - nodejs
  - numpy
  - pandas
  - pip
  - pre-commit
  - prefect<2.0
  - pyarrow
  - pygmt
  - regionmask
  - s3fs
  - shapely
  - thefuzz
  - tippecanoe
  - tqdm
  - xarray
  - xesmf
  - zarr
  - rioxarray
  - requests
  - pip:
      - carbonplan-forest-offsets
      - carbonplan-styles
      - carbonplan-data
      - censusgeocode
      - git+https://github.com/carbonplan/ndpyramid.git
