name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 30
    container:
      image: quay.io/carbonplan/forest-offsets-fires:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          python -m pip install -e .[dev]
          python -m pip list

      - name: Run tests
        run: |
          python -m pytest tests --verbose
